x-ollama: &ollama
  extra_hosts:
    - "host.containers.internal:host-gateway"
  environment:
    - OLLAMA_HOST=http://host.containers.internal:11434
    - PYTHONPATH=/workspace

services:
  vanilla:
    build:
      context: .
      dockerfile: Dockerfile.vanilla
    volumes:
      - .:/workspace
    <<: *ollama
    working_dir: /workspace
    entrypoint: ["python"]

  lc:
    build:
      context: .
      dockerfile: Dockerfile.lc
    volumes:
      - .:/workspace
    <<: *ollama
    working_dir: /workspace
    entrypoint: ["python"]

  crewai:
    build:
      context: .
      dockerfile: Dockerfile.crewai
    volumes:
      - .:/workspace
    <<: *ollama
    working_dir: /workspace
    entrypoint: ["python"]
