"""
Human-in-the-loop types.
A Plan is a structured delegation proposal generated by the orchestrator.
The user approves or rejects the plan before any subtasks are executed.

A Subtask can be either:
- Agent subtask: `{"agent": "...", "task": "..."}` — delegates to a specialist agent
- MCP subtask:   `{"mcp_server": "...", "tool_name": "...", "args": {...}}` — direct MCP call
"""

import json
from dataclasses import dataclass, field


VALID_AGENTS = (
    "WebSearchAgent",
    "CodeExecutionAgent",
    "DocumentAgent",
    "APIAgent",
    "DataAgent",
)


@dataclass(frozen=True)
class Subtask:
    agent: str = ""
    task: str = ""
    mcp_server: str = ""
    tool_name: str = ""
    args: dict = field(default_factory=dict)

    @property
    def is_mcp(self) -> bool:
        return bool(self.mcp_server and self.tool_name)

    def to_dict(self) -> dict:
        if self.is_mcp:
            return {
                "mcp_server": self.mcp_server,
                "tool_name": self.tool_name,
                "args": self.args,
            }
        return {"agent": self.agent, "task": self.task}


@dataclass
class Plan:
    subtasks: list[Subtask] = field(default_factory=list)
    reasoning: str = ""

    def to_json(self) -> str:
        return json.dumps(
            {
                "reasoning": self.reasoning,
                "subtasks": [s.to_dict() for s in self.subtasks],
            },
            ensure_ascii=False,
        )

    @classmethod
    def from_json(cls, text: str) -> "Plan":
        data = json.loads(text)
        if not isinstance(data, dict):
            raise ValueError("Plan JSON must be an object")
        raw_subtasks = data.get("subtasks", [])
        if not isinstance(raw_subtasks, list) or not raw_subtasks:
            raise ValueError("Plan must contain a non-empty 'subtasks' list")
        subtasks = []
        for i, item in enumerate(raw_subtasks):
            if not isinstance(item, dict):
                raise ValueError(f"Subtask {i} must be an object")
            subtasks.append(_parse_subtask(i, item))
        return cls(
            subtasks=subtasks,
            reasoning=str(data.get("reasoning", "")).strip(),
        )

    def format(self) -> str:
        lines = ["Plan:", ""]
        if self.reasoning:
            lines.append(f"Reasoning: {self.reasoning}")
            lines.append("")
        for i, s in enumerate(self.subtasks, 1):
            if s.is_mcp:
                args_str = ", ".join(f"{k}={v!r}" for k, v in s.args.items())
                lines.append(f"  {i}. [MCP:{s.mcp_server}.{s.tool_name}] {args_str}")
            else:
                lines.append(f"  {i}. [{s.agent}] {s.task}")
        return "\n".join(lines)


def _parse_subtask(index: int, item: dict) -> Subtask:
    if "mcp_server" in item or "tool_name" in item:
        mcp_server = str(item.get("mcp_server", "")).strip()
        tool_name = str(item.get("tool_name", "")).strip()
        if not mcp_server or not tool_name:
            raise ValueError(
                f"Subtask {index}: MCP subtask needs both 'mcp_server' and 'tool_name'"
            )
        args = item.get("args", {})
        if not isinstance(args, dict):
            raise ValueError(f"Subtask {index}: 'args' must be an object")
        return Subtask(mcp_server=mcp_server, tool_name=tool_name, args=args)

    agent = str(item.get("agent", "")).strip()
    task = str(item.get("task", "")).strip()
    if agent not in VALID_AGENTS:
        raise ValueError(
            f"Subtask {index} has invalid agent '{agent}'. "
            f"Choose from: {list(VALID_AGENTS)}"
        )
    if not task:
        raise ValueError(f"Subtask {index} has empty 'task'")
    return Subtask(agent=agent, task=task)


@dataclass(frozen=True)
class ApprovalDecision:
    approved: bool
    feedback: str | None = None
