"""
Human-in-the-loop types.
A Plan is a structured delegation proposal generated by the orchestrator.
The user approves or rejects the plan before any subtasks are executed.
"""

import json
from dataclasses import dataclass, field


VALID_AGENTS = (
    "WebSearchAgent",
    "CodeExecutionAgent",
    "DocumentAgent",
    "APIAgent",
    "DataAgent",
)


@dataclass(frozen=True)
class Subtask:
    agent: str
    task: str

    def to_dict(self) -> dict:
        return {"agent": self.agent, "task": self.task}


@dataclass
class Plan:
    subtasks: list[Subtask] = field(default_factory=list)
    reasoning: str = ""

    def to_json(self) -> str:
        return json.dumps(
            {
                "reasoning": self.reasoning,
                "subtasks": [s.to_dict() for s in self.subtasks],
            },
            ensure_ascii=False,
        )

    @classmethod
    def from_json(cls, text: str) -> "Plan":
        data = json.loads(text)
        if not isinstance(data, dict):
            raise ValueError("Plan JSON must be an object")
        raw_subtasks = data.get("subtasks", [])
        if not isinstance(raw_subtasks, list) or not raw_subtasks:
            raise ValueError("Plan must contain a non-empty 'subtasks' list")
        subtasks = []
        for i, item in enumerate(raw_subtasks):
            if not isinstance(item, dict):
                raise ValueError(f"Subtask {i} must be an object")
            agent = item.get("agent", "").strip()
            task = item.get("task", "").strip()
            if agent not in VALID_AGENTS:
                raise ValueError(
                    f"Subtask {i} has invalid agent '{agent}'. "
                    f"Choose from: {list(VALID_AGENTS)}"
                )
            if not task:
                raise ValueError(f"Subtask {i} has empty 'task'")
            subtasks.append(Subtask(agent=agent, task=task))
        return cls(
            subtasks=subtasks,
            reasoning=str(data.get("reasoning", "")).strip(),
        )

    def format(self) -> str:
        lines = ["Plan:", ""]
        if self.reasoning:
            lines.append(f"Reasoning: {self.reasoning}")
            lines.append("")
        for i, s in enumerate(self.subtasks, 1):
            lines.append(f"  {i}. [{s.agent}] {s.task}")
        return "\n".join(lines)


@dataclass(frozen=True)
class ApprovalDecision:
    approved: bool
    feedback: str | None = None
